// src/livecodes/templates/starter/react-starter.ts
import type { Template } from '../../models';

export const reactStarter: Template = {
  name: 'react',
  title: window.deps.translateString('templates.starter.react', 'React Starter'),
  thumbnail: 'assets/templates/react.svg',
  activeEditor: 'script',
  markup: {
    language: 'html',
    content: '',
  },
  style: {
    language: 'css',
    content: `
.container,
.container button {
  background: #fff;
  border-radius: 0.5em;
  color: #111;
  padding: 1em;
  text-align: center;
  font: 1em sans-serif;
}
.logo {
  width: 150px;
}
`.trimStart(),
  },
  script: {
    language: 'jsx',
    content: `
import { useState } from "react";

function Counter(props) {
  const [count, setCount] = useState(0);
  return (
    <div className="container">
      <h1>Hello, {props.name}!</h1>
      <img className="logo" alt="logo" src="{{ __livecodes_baseUrl__ }}assets/templates/react.svg" />
      <p>You clicked {count} times.</p>
      <button onClick={() => setCount(count + 1)}>Click me</button>
    </div>
  );
}

export default function App() {
  return <Counter name="React" />;
}
`.trimStart(),
  },
  stylesheets: [],
  scripts: [],
  cssPreset: '',
  imports: {},
  types: {},
};

// src/livecodes/templates/starter/lit-starter.ts
import type { Template } from '../../models';

export const litStarter: Template = {
  name: 'lit',
  title: window.deps.translateString('templates.starter.lit', 'Lit Starter'),
  thumbnail: 'assets/templates/lit.svg',
  activeEditor: 'script',
  markup: {
    language: 'html',
    content: `
<my-counter name="Lit"></my-counter>
`.trimStart(),
  },
  style: {
    language: 'css',
    content: '',
  },
  script: {
    language: 'typescript',
    content: `
import { LitElement, html, css } from "lit";
import { customElement, property } from "lit/decorators.js";
import { SignalWatcher, signal } from "@lit-labs/preact-signals";

@customElement("my-counter")
export class SignalExample extends SignalWatcher(LitElement) {
  @property()
  name = "World";

  count = signal(0);

  private _onClick() {
    this.count.value = this.count.value + 1;
  }

  render() {
    return html\`
      <h1>Hello, \${this.name}!</h1>
      <img class="logo" alt="logo" src="{{ __livecodes_baseUrl__ }}assets/templates/lit.svg" />
      <p>You clicked \${this.count.value} times.</p>
      <button @click=\${this._onClick}>Click me</button>
    \`;
  }

  static styles = css\`
    :host {
      display: flex;
      flex-direction: column;
      align-items: center;
      background: #fff;
      border-radius: 0.5em;
      color: #111;
      padding: 1em;
      text-align: center;
      font: 1em sans-serif;
    }
    :host, button {
      font: 1em sans-serif;
    }
    .logo {
      width: 150px;
    }
  \`;
}
`.trimStart(),
  },
  customSettings: {
    typescript: {
      experimentalDecorators: true,
      useDefineForClassFields: false,
    },
  },
};
